import { Component, Input } from '@angular/core';
import { switchMap, tap, timer } from 'rxjs';
import { DeviceDto } from 'src/app/core/models/autogenerated/dtos/deviceDto';
import { BikeRentService } from 'src/app/core/services/bike-rent.service';

@Component({
  selector: 'app-bike-locker',
  templateUrl: './bike-locker.component.html',
  styleUrls: ['./bike-locker.component.scss'],
})
export class BikeLockerComponent {
  @Input() device: DeviceDto;
  public loading: boolean = false;

  constructor(private bikeRentService: BikeRentService) {}

  public unlockDevice() {
    this.loading = true;

    timer(100) //simulate delay
      .pipe(
        switchMap((e) =>
          this.bikeRentService.unlockDevice(this.device.deviceName).pipe(
            tap((e) => {
              // this.loading = false;
            })
          )
        )
      )
      .subscribe((e) => {});
  }
}
